name: Publish NuGet Package

on:
  workflow_dispatch:
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # fetch all history for all tags, required for NBGV versioning

    - name: setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build the package
      run: dotnet pack src/AhoCorasick.Net/AhoCorasick.Net.csproj --configuration Release

    - name: Publish to GitHub Packages
      run: dotnet nuget push **/*.nupkg --source github --api-key ${{ secrets.GITHUB_TOKEN }}

    - name: Done
      run: echo "Nuget package published to Github packages"
