name: Publish NuGet Package

on:
  push:
    tags:
      - 'v0.8.0'
  workflow_dispatch:
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build the package
      run: dotnet pack src/AhoCorasick.Net/AhoCorasick.Net.csproj --configuration Release

    - name: Publish to GitHub Packages
      run: dotnet nuget push **/*.nupkg --source github --api-key ${{ secrets.GITHUB_TOKEN }}

    - name: Upload package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: AhoCorasick.Net.0.8.0
        path: '**/*.nupkg'

    - name: Done
      run: echo "Nuget package published to Github packages"
